# Generated by Django 4.2.5 on 2023-12-05 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='approval_comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(blank=True, choices=[('PE', 'Pending'), ('WT', 'Waiting'), ('OP', 'Onprogress'), ('CO', 'Completed'), ('AP', 'Approved'), ('RE', 'Rejected')], default='PE', max_length=10, null=True),
        ),
    ]
