# Generated by Django 4.2.5 on 2023-12-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allschedule',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
