# Generated by Django 4.2.5 on 2023-12-19 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='assign_roles',
            new_name='assign_permissions',
        ),
    ]
