# Generated by Django 4.2.5 on 2023-12-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('MA', 'Manager'), ('TL', 'Team Leader'), ('EN', 'Engineer'), ('BA', 'Bank User')], default='EN', max_length=40),
        ),
    ]
