# Generated by Django 4.2.5 on 2023-11-15 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0002_schedule_schedule_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='terminal',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
