# Generated by Django 4.2.5 on 2023-12-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0002_allschedule_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(blank=True, choices=[('PE', 'Pending'), ('WT', 'Waiting'), ('OP', 'Onprogress'), ('SB', 'Sumitted'), ('AP', 'Approved'), ('RE', 'Rejected')], default='PE', max_length=10, null=True),
        ),
    ]
