# Generated by Django 4.2.5 on 2023-12-04 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0002_allschedule_schedule_list_schedule_schedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedule_List',
        ),
    ]
