# Generated by Django 4.2.5 on 2024-01-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0003_moti_district_terminal_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='moti_district',
            name='district_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='closed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
