# Generated by Django 4.2.5 on 2023-12-04 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0003_delete_schedule_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allschedule',
            name='schedule_by',
        ),
        migrations.AddField(
            model_name='allschedule',
            name='scheduled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
