# Generated by Django 4.2.5 on 2023-11-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0003_bank_created_date_schedule_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='terminals',
            field=models.ManyToManyField(blank=True, related_name='schedules', to='pm.terminal'),
        ),
    ]
