# Generated by Django 4.2.5 on 2023-11-15 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0004_alter_schedule_terminals'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['end_date']},
        ),
        migrations.AlterModelOptions(
            name='terminal',
            options={'ordering': ['terminal_name']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['first_name', 'last_name']},
        ),
    ]
