# Generated by Django 4.2.5 on 2023-12-07 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0004_alter_schedule_bank_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='bank_name',
        ),
    ]
