# Generated by Django 4.2.5 on 2023-10-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0004_alter_user_date_joined_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(blank=True, choices=[('PE', 'PENDING'), ('OP', 'ONPROGRESS'), ('CO', 'COMPLETED')], default='PE', max_length=2, null=True),
        ),
    ]
