# Generated by Django 4.2.5 on 2024-02-07 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0004_moti_district_district_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terminal',
            name='moti_district',
        ),
    ]
