# Generated by Django 4.2.5 on 2023-11-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0005_alter_schedule_options_alter_terminal_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='terminals',
            field=models.ManyToManyField(blank=True, to='pm.terminal'),
        ),
    ]
