# Generated by Django 4.2.5 on 2023-10-17 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0005_alter_schedule_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_User',
        ),
        migrations.AddField(
            model_name='schedule',
            name='comment',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='priority',
            field=models.CharField(blank=True, choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(blank=True, choices=[('PE', 'PENDING'), ('OP', 'ONPROGRESS'), ('CO', 'COMPLETED')], default='PE', max_length=10, null=True),
        ),
    ]
