# Generated by Django 4.2.5 on 2024-03-04 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0005_remove_terminal_moti_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='moti_district',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='remaining_days',
            field=models.IntegerField(blank=True, default=90, null=True),
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pm.bank')),
                ('moti_district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pm.moti_district')),
                ('schedule_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pm.schedule')),
            ],
        ),
    ]
