# Generated by Django 4.2.5 on 2023-12-11 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0005_remove_schedule_bank_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='bank_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='banks', to='pm.bank'),
        ),
    ]
