# Generated by Django 4.2.5 on 2024-03-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0006_moti_district_city_schedule_remaining_days_statistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='rejected_comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
