# Generated by Django 4.2.5 on 2024-03-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0007_schedule_rejected_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='remaining_days',
            field=models.CharField(blank=True, default=90, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(blank=True, choices=[('PE', 'Pending'), ('WT', 'Waiting'), ('OP', 'Onprogress'), ('SB', 'Submitted'), ('AP', 'Approved'), ('RE', 'Rejected')], default='PE', max_length=10, null=True),
        ),
    ]
