# Generated by Django 4.2.5 on 2024-03-18 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0008_alter_schedule_remaining_days_alter_schedule_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='remaining_days',
        ),
    ]
