# Generated by Django 4.2.5 on 2024-03-18 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0009_remove_schedule_remaining_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='terminal',
            field=models.ForeignKey(help_text='Select Terminal', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='terminals', to='pm.terminal'),
        ),
    ]
