# Generated by Django 4.2.5 on 2023-12-14 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0010_user_is_active_alter_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('MA', 'Manager'), ('SC', 'Scheduler'), ('EN', 'Engineer'), ('BA', 'Bank User')], max_length=40),
        ),
    ]
