# Generated by Django 4.2.5 on 2023-12-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0011_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('MA', 'Manager'), ('TL', 'Team Leader'), ('EN', 'Engineer'), ('BA', 'Bank User')], max_length=40),
        ),
    ]
