# Generated by Django 4.2.5 on 2023-12-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0012_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activate_bank',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='inactivate_bank',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
