# Generated by Django 4.2.5 on 2023-12-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0013_user_activate_bank_user_inactivate_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Photo',
        ),
        migrations.AddField(
            model_name='user',
            name='view_analysis',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, help_text='Photo', null=True, upload_to='profile_pics'),
        ),
    ]
